### ISSUE TITLE
Cannot find module 'bluetooth-hci-socket' when starting ruuvitag

### ISSUE THREAD

**Issue by juuso123** [akx/hass-ruuvitag#23]
Hi,
I'm Using hassio Resin OS 2.3.0+rev1, Supervisor 220 and Home-assistant 109.3.
Host is a raspberry pi 3b with usb bluetooth dongle.

Is there any way to get it working? Any help would be appreciated. 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
internal/modules/cjs/loader.js:796
    throw err;
    ^
Error: Cannot find module 'bluetooth-hci-socket'
Require stack:
- /app/node_modules/noble/lib/hci-socket/hci.js
- /app/node_modules/noble/lib/hci-socket/bindings.js
- /app/node_modules/noble/lib/resolve-bindings.js
- /app/node_modules/noble/index.js
- /app/node_modules/node-ruuvitag/ruuvi.js
- /app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/noble/lib/hci-socket/hci.js',
    '/app/node_modules/noble/lib/hci-socket/bindings.js',
    '/app/node_modules/noble/lib/resolve-bindings.js',
    '/app/node_modules/noble/index.js',
    '/app/node_modules/node-ruuvitag/ruuvi.js',
    '/app/app.js'
[cmd] node exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by akx** [comment]
Do you have a container build log at hand?

**Comment by juuso123** [comment]
Hi, this is what I got when I tried to build it manually with command:

hass-ruuvitag $ docker build --tag hass:1.0 .
Sending build context to Docker daemon    833kB
Step 1/17 : ARG BUILD_FROM
 --->
Step 2/17 : FROM $BUILD_FROM as build
 --->
Step 3/17 : ENV LANG C.UTF-8
 ---> Using cache
 ---> 57f6bde8f939
Step 4/17 : RUN apk add --no-cache nodejs libusb-dev bluez-dev linux-headers eudev-dev
 ---> Running in 0ceb5723c23f
container_linux.go:263: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"
oci runtime error: container_linux.go:263: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

**Comment by akx** [comment]
Sorry for not following up on this sooner. A manual build would be
```
docker build --build-arg BUILD_FROM=homeassistant/amd64-base:latest .
```
(i.e. you need to specify the source image)
